### ISSUE TITLE
Please share the pretrained if possible. I need to fine tune it on my custom dataset.

### ISSUE THREAD

**Issue by hacker009-sudo** [ReplicAI/SynLibras#2]
Also, please share the data pre-processing steps.

Like, once we will extract 2D poses from the images/video then how we need to modify these 2D key-points before passing as a training dataset to the model.

**Comment by wellingtonfs** [comment]
Hello, the pre-trained model can be found at the following link: [pre-trained model](https://drive.google.com/file/d/1i5nQyz8tjFv1JZ2P4NQOoiwnFutbyirl/view?usp=sharing). I have already updated the README with this link.

you should extract the poses using OpenPose and place the JSON files in the 'keypoints' folder. An example dataset can be found here: [dataset example](https://drive.google.com/file/d/1JlMxS9t4oWG7NXkSb2F0sQbxSuVXnrey/view?usp=sharing)

Finally, this notebook demonstrates how to run and test the model with the sample dataset: [colab](https://colab.research.google.com/drive/1VVGzYW0FGUxmdg-VDpAj7tQX7zBeZxST?usp=sharing)

I hope this helps.

**Comment by hacker009-sudo** [comment]
Thanks @wellingtonfs , for sharing the pretrained model and sample dataset. It will help us to better understand the functionality. Closing this issue.
