### ISSUE TITLE
Pose Transfer is not working. Please help

### ISSUE THREAD

**Issue by hacker009-sudo** [ReplicAI/SynLibras#3]
Please share the command for pose transfer like you have shared for reconstruction.

cc - @rodrigodebem  @wellingtonfs @Girafandrew @Luca-Barboza-Mendonca

**Comment by wellingtonfs** [comment]
Hello, I've just realized an issue with this script. I will update it as soon as possible. Once I have updated the script, I will send the example command to perform the transfer.

**Comment by hacker009-sudo** [comment]
Thanks @wellingtonfs . I was debugging the issue and found that problem is with **__make_gauss_list** function in **data/pose.py** file.

Yes, please share the updated script once it is ready. Will be really really helpful.

Thanks again.

 cc - @rodrigodebem, @Girafandrew , @Luca-Barboza-Mendonca

**Comment by hacker009-sudo** [comment]
@wellingtonfs ,
Can you please guide me what is the issue with the pose-transfer script. I am trying to resolve it. So, if you could give me some hints as to which function in the code is not working then it will be easy for me to debug it. 

@rodrigodebem @Girafandrew @Luca-Barboza-Mendonca

**Comment by wellingtonfs** [comment]
Hi,

The script has been updated, as well as the README explaining how to use it. In the README, you will also find a Colab notebook showing how to perform the transfer.

Take care.

**Comment by hacker009-sudo** [comment]
Amazing Work!!!

Thanks, I could perform the pose transfer on the sample dataset present in this repo. However, on custom dataset still there is some issue but I will fine tune your model on my custom dataset and I am sure that issue will be resolved.

Again, Thanks for this amazing contribution.

cc - @rodrigodebem @Girafandrew  @Luca-Barboza-Mendonca
